<!DOCTYPE html>
<html lang = "es">
<head>
    <meta charset = "UTF-8"/>
    <h1 style="color:white; text-align: center "> Registro Actualizado Correctamente </h1>
	<title>Registro Actualizado</title>
    <link type="text/css" rel="stylesheet" href="css/z.css" media="screen"/>
</head>
<body>
<font color="White" face="Verdana" size=4>
    <?php 
         echo "<br> Hemos actualizado sus datos. Gracias. Hasta pronto."."<br>";
    ?>
</font>
</body>
</html>